### ISSUE TITLE
Docker Command failed

### ISSUE THREAD

**Issue by Michaelmantion** [openaudible/openaudible_docker#8]
docker run -d --rm -it -v $HOME/OpenAudible:/config/OpenAudible -p 3000:3000 -e PGID=`id -g` -e PUID=`id -u` --name openaudible openaudible/openaudible:latest

unknown shorthand flag: 'g' in -g`
See 'docker run --help'.

just installed newest version openaudible docker and got error above when running command in instruction.  Will try app image.

**Comment by openaudible** [comment]
It looks like the command is supposed to be getting the puid and pgid from the command line is failing. Are you on linux and have bash installed?

What happens when you run:
```
id -u
id -g
```
That should output two numbers... But if it gives you an error, run `man id` and see how to get just the user id and group id using the id command.
